### ISSUE TITLE
Change the layout to tabs

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/inscribe#1]
as in https://1satordinals.com/inscribe

**Comment by yusufidimaina9989** [comment]
Done.      https://github.com/sCrypt-Inc/inscribe/pull/4#issue-2023346318

**Comment by xhliu** [comment]
Please center the tabs. Currently they are aligned left.
<img width="1184" alt="image" src="https://github.com/sCrypt-Inc/inscribe/assets/1017252/9b637d7a-af27-4b80-b461-c85e71ffef9c">
